#+FILETAGS: :project:
* Engulped
Engulped provides utilities for defining some common build build tasks for es6 using babel and mocha.
I kept needing the same tasks in many of my projects, so this tool makes it possible to add each in as needed.

** Usage
The most common usage is to add all the default tasks. To do so, your gulpfile would look like the following
#+begin_src javascript
var gulp     = require('gulp')
var Engulped = require('engulped')

var engulped = Engulped.withDefaultTasks(gulp)
gulp.task('default',['test',build'])
#+end_src

This automatically adds many tasks to gulp. The default task added uses the added tasks oo run all specs with mocha and transpiles to es6 to es5.


You can then optionally overwrite them as needed
#+begin_src javascript
  gulp.task('clean,function(){
    console.log('feeling clean')
  })

#+end_src

You can also reference the original function used to generate the tasks via the -tasks- method.
For example, here's how you'd overwrite clean with the same implementation:

#+begin_src javascript
var tasks = engulped.tasks()
gulp.task('clean',tasks.clean())
#+end_src

Some taskbuilding functions have parameters they accept, take a look at -lib/addDefaultTasks.js- and -lib/taskBuilders- for more information.

** What are the tasks
*** clean
Cleans the directory of files created by transpiling
*** build
Transpile source files in -src- from es6 to es5 (src -> dest) (via babel)
*** test
Run all specs in test directory (es6 registered) (via mocha)
*** watch
Runs the default task on any file changes (via nodemon)

** I don't want all these tasks added
Then you can create it with the constructor instead, and add them manually
#+begin_src javascript
var gulp     = require('gulp')
var Engulped = require('engulped')

var engulped = new Engulped(gulp)
var tasks = engulped.tasks()

gulp.task('clean',tasks.clean())
#+end_src


** I want different src and dest directories for my build
You can pass a configuration as the second parameter to the constructor or Engulped.withDefaultTasks. The default config looks something like:
#+begin_src javascript
  {argv : process.argv,
   paths : {
     script : {
       src  : './lib/',
       dest : './dist/',
       pattern : '/**/*.js'
     },
     test : {
       src  : './test/',
       pattern : '/**/**Spec.js'
     }
   }
#+end_src

** Planned
*** TODO Add documention for adding custom task builders
*** TODO Add documention for task builders
